apiVersion: v1
kind: Service
metadata:
   name: emp-data
   labels:
     run: emp-data
spec:
   ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
   type: NodePort
   selector:
     run: emp-data

